name: Publish to PyPI and GitHub

on:
  push:
#    branches:
#      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 # Adjust to your Python version
      - name: current_version
        run: echo "current_version=$(python -c 'from yourpackage import __version__; print(__version__)')" >> $GITHUB_ENV

      - name: setup bump
        run: |
          set -x
          echo ${{  github.event.pusher.name  }}
          pip install bump2version twine
          git config --global user.name "${{ github.event.pusher.name }}"
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global pull.rebase false

      - name: Increment version
        run: bump2version patch # or 'minor' or 'major'

      - name: Build and upload to PyPI
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

      - name: Create GitHub tag
        run: |
          git tag v$(python -c "from yourpackage import __version__; print(__version__)")
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
